# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Delirium Coder
email: info@deliriumcoder.com
description: 'Desde 2012 ayudamos a startups, instituciones y empresas en el diseño, desarrollo e implantación de soluciones tecnológicas que les permitan alcanzar sus objetivos.'
baseurl: '' # the subpath of your site, e.g. /blog
url: 'http://www.deliriumcoder.com' # the base hostname & protocol for your site
destination: 'www'

# Build settings
markdown: kramdown

collections:
  projects:
    output: true
    permalink: /proyectos/:path/

sass:
  sass_dir: _sass

exclude: ['Gemfile.lock', 'Gemfile', 'config', 'package.json', 'node_modules', 'gulpfile.js']
